name: make
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: hse
    - uses: actions/checkout@v2
      with:
        path: mpool
        repository: hse-project/mpool
    - uses: lukka/get-cmake@latest
    - name: make libmpool
      run: |
        sudo apt-get install autopoint gettext uuid-dev uuid-runtime
        make debug config
        make debug -j
        sudo make install
      working-directory: mpool
    - name: make hse
      run: |
        sudo apt-get install autopoint gettext uuid-dev uuid-runtime libmicrohttpd-dev libmicrohttpd12 liburcu6 liburcu-dev
        make debug config
        make debug -j
        make debug testp
      working-directory: hse
