name: make
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: hse
    - uses: actions/checkout@v2
      with:
        path: mpool
        repository: hse-project/mpool
    - uses: lukka/get-cmake@latest
    - run: |
        make release config
        make release
        sudo make install
      working-directory: mpool
